version: "3.8"

networks:
  silverstripe-environment:

volumes:
  db-data:

services:

  database:
    image: mysql:latest
    container_name: mysql-container
    hostname: database
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
    networks:
      - silverstripe-environment

  silverstripe81:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php81-container
    volumes:
      - .:/var/www/html
    ports:
      - 90:80
    depends_on:
      - database
    networks:
      - silverstripe-environment